[functions.create-memo]
enabled = true
verify_jwt = false
import_map = "./functions/create-memo/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-memo/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-memo/*.html" ]

[functions.list-memos]
enabled = true
verify_jwt = false
import_map = "./functions/list-memos/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/list-memos/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/list-memos/*.html" ]

[functions.get-memo-by-id]
enabled = true
verify_jwt = false
import_map = "./functions/get-memo-by-id/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-memo-by-id/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-memo-by-id/*.html" ]

[functions.update-memo]
enabled = true
verify_jwt = false
import_map = "./functions/update-memo/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-memo/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-memo/*.html" ]

[functions.delete-memo]
enabled = true
verify_jwt = false
import_map = "./functions/delete-memo/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-memo/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-memo/*.html" ]

[functions.process-manual-function]
enabled = true
verify_jwt = false
import_map = "./functions/process-manual-function/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-manual-function/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-manual-function/*.html" ]

[functions.upload-manual-function]
enabled = true
verify_jwt = false
import_map = "./functions/upload-manual-function/deno.json"
entrypoint = "./functions/upload-manual-function/index.ts"

[functions.suggest-next-actions]
enabled = true
verify_jwt = false
import_map = "./functions/suggest-next-actions/deno.json"
entrypoint = "./functions/suggest-next-actions/index.ts"

[functions.debug-auth]
enabled = true
verify_jwt = false
import_map = "./functions/debug-auth/deno.json"
entrypoint = "./functions/debug-auth/index.ts"

[functions.delete-file-function]
enabled = true
verify_jwt = false
import_map = "./functions/delete-file-function/deno.json"
entrypoint = "./functions/delete-file-function/index.ts"
