name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - develop  # developブランチ -> 開発環境
      - main     # mainブランチ -> 本番環境

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      # ブランチに応じてプロジェクトIDを切り替え
      PROJECT_ID: ${{ github.ref == 'refs/heads/main' && secrets.SUPABASE_PROJECT_ID_PRODUCTION || secrets.SUPABASE_PROJECT_ID_DEVELOPMENT }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy All Edge Functions
        run: |
          echo "Deploying to ${{ github.ref == 'refs/heads/main' && 'PRODUCTION' || 'DEVELOPMENT' }} environment..."
          echo "Target Project ID: $PROJECT_ID"
          
          # 環境ごとのカスタム環境変数を設定してデプロイ
          # SUPABASE_ で始まるものは自動設定されるので、ここでは設定しない
          echo "Setting custom secrets..."
          supabase secrets set GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" --project-ref $PROJECT_ID
          supabase secrets set GOOGLE_VISION_API_KEY="${{ secrets.GOOGLE_VISION_API_KEY }}" --project-ref $PROJECT_ID
          supabase secrets set OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" --project-ref $PROJECT_ID
          # 他にカスタムの環境変数があればここに追加（例: RESEND_API_KEYなど、ただしEdge Functionで使う場合のみ）
          echo "Custom secrets set."
          
          # Edge Functionsをデプロイ
          echo "Deploying functions..."
          supabase functions deploy --project-ref $PROJECT_ID --no-verify-jwt
          echo "Deployment of all functions to ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }} completed."