name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - develop  # developブランチへのpushをトリガーにする
      - fix/function-size # developブランチへのpushに加え、fix/function-sizeブランチへのpushもトリガーにする

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Supabase Deployment # オプション: 環境名を指定
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest # もし特定のバージョンを指定したい場合は変更 (例: '1.167.4')

      - name: Deploy All Edge Functions
        run: |
          echo "Deploying all Edge Functions..."
          supabase functions deploy --project-ref $PROJECT_ID --no-verify-jwt
          echo "Deployment of all functions attempted."